/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_h264_decode2_FFmpegNative */

#ifndef _Included_com_h264_decode2_FFmpegNative
#define _Included_com_h264_decode2_FFmpegNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_h264_decode2_FFmpegNative
 * Method:    Init
 * Signature: (Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Init
        (JNIEnv *, jobject, jstring);

/*
 * Class:     com_h264_decode2_FFmpegNative
 * Method:    Decode2RGB
 * Signature: ([B)I
 */
JNIEXPORT jint JNICALL Decode2RGB
  (JNIEnv *, jobject, jbyteArray);

#ifdef __cplusplus
}
#endif
#endif
